validator:
  enableNetworkPolicy: false
  rust_log: debug,hyper=off

fullnode:
  # at most one VFN per validator, depending on numFullnodeGroups
  groups:
  - name: fullnode
    replicas: 1
  rust_log: debug,hyper=off

# Make all services internal NodePort and open all ports
# NodePort is required for ChaosMesh to function correctly: https://github.com/chaos-mesh/chaos-mesh/issues/3278#issuecomment-1134248492
service:
  validator:
    external:
      type: "NodePort"
    internal:
      type: "NodePort"
    enableRestApi: true
    enableMetricsPort: true

  fullnode:
    external:
      type: "NodePort"
    internal:
      type: "NodePort"
    enableRestApi: true
    enableMetricsPort: true

# to give HAProxy access to more resources, schedule it on validators nodegroup
# in the long term, we should consider giving the "utilities" nodegroup more resources
# or removing it from the reference implementation entirely
haproxy:
  nodeSelector:
    eks.amazonaws.com/nodegroup: "validators"

# always assume we're spinning up a testnet and doing genesis rather than using the single validator test mode
loadTestGenesis: false
